### ISSUE TITLE
Closing a parent area should close any opened areas nested within it.

### ISSUE THREAD

**Issue by sideshowbarker** [BradNeuberg/stretchtext.js#1]
When I close an area, stretchtextjs should also close any opened areas nested within it.

**Comment by jomido** [comment]
I actually prefer the case where parent state change does not affect child state. At most, the default behaviour should be a configuration option (or a parameter).

**Comment by BradNeuberg** [comment]
@jomido I'd rather go with the solution that has the best UX, and it seems like closing the parent should close the children, as that's what most people would expect and it makes it easier to manage deeply nested stretchtext better. I meant to do it originally I just didn't have the time for the original release.

**Comment by jomido** [comment]
OK. Would it be possible to make this configurable? I suppose there are many different ways to do that. I understand that adding in configurable options has a way of negatively affecting the elegance and/or simplicity of a code base. So if this doesn't become a priority for you, it's OK. If the project I have in mind for utilizing stretchtext,js comes about, I can always contribute. :)

**Comment by sideshowbarker** [comment]
Going ahead and closing this as stale. Of course feel free to re-open at any time.
